export const SHOW_WELCOME_PAGE = 'SHOW_WELCOME_PAGE';
export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
export const HIDE_ERROR_MESSAGE = 'HIDE_ERROR_MESSAGE';
export const SHOW_DASHBOARD = 'SHOW_DASHBOARD';
export const SHOW_SEND_OTP_PAGE = 'SHOW_SEND_OTP_PAGE';
export const SHOW_VERIFY_OTP_PAGE = 'SHOW_VERIFY_OTP_PAGE';
export const VERIFY_OTP = 'VERIFY_OTP';
