/* auth action types */
export const SHOW_WELCOME_PAGE = 'SHOW_WELCOME_PAGE';
export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
export const SHOW_DASHBOARD = 'SHOW_DASHBOARD';
export const SHOW_SEND_OTP_PAGE = 'SHOW_SEND_OTP_PAGE';
export const SHOW_VERIFY_OTP_PAGE = 'SHOW_VERIFY_OTP_PAGE';
export const VERIFY_OTP = 'VERIFY_OTP';
export const LOGOUT = 'LOGOUT';
export const SHOW_RESET_EMAIL_CONFIRMATION = 'SHOW_RESET_EMAIL_CONFIRMATION';
export const CLEAR_COMPONENT_KEY = 'CLEAR_COMPONENT_KEY';
export const RESET_PASSWORD_CODE_VERIFIED = 'RESET_PASSWORD_CODE_VERIFIED';
/* common */
export const HIDE_ERROR_MESSAGE = 'HIDE_ERROR_MESSAGE';

/* car profile action types */
export const SET_CAR_PROFILE = 'SET_CAR_PROFILE';
export const LIST_CAR_PROFILES = 'LIST_CAR_PROFILES';
export const VIEW_CAR_PROFILE = 'VIEW_CAR_PROFILE';
export const DELETE_CAR_PROFILE = 'DELETE_CAR_PROFILE';
